services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - socket-server
    networks:
      - hangman-network
    environment:
      - SOCKET_SERVER_URL=http://socket-server:3000

  socket-server:
    build: ./socket-server
    ports:
      - "3000:3000"
    depends_on:
      - game-service
      - chat-service
    networks:
      - hangman-network
    environment:
      - GAME_SERVICE_URL=http://game-service:3001
      - CHAT_SERVICE_URL=http://chat-service:3002

  game-service:
    build: ./game-service
    ports:
      - "3001:3001"
    networks:
      - hangman-network

  chat-service:
    build: ./chat-service
    ports:
      - "3002:3002"
    networks:
      - hangman-network

networks:
  hangman-network:
    driver: bridge