version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hangman-network

  db-service:
    build: ./db-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    networks:
      - hangman-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/hangman

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - client
      - game-service
      - chat-service
      - socket-server
    networks:
      - hangman-network

  client:
    build: ./client
    expose:
      - "80"
    environment:
      - NODE_ENV=development
      - SOCKET_SERVER_URL=http://socket-server:3000
    networks:
      - hangman-network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  game-service:
    build: ./game-service
    expose:
      - "3001"
    environment:
      - DB_SERVICE_URL=http://db-service:3003
      - NODE_ENV=development
    networks:
      - hangman-network
    volumes:
      - ./game-service:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  game-service-2:
    build: ./game-service
    expose:
      - "3001"
    environment:
      - NODE_ENV=development
      - DB_SERVICE_URL=http://db-service:3003
    networks:
      - hangman-network
    volumes:
      - ./game-service:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  game-service-3:
    build: ./game-service
    expose:
      - "3001"
    environment:
      - NODE_ENV=development
      - DB_SERVICE_URL=http://db-service:3003
    networks:
      - hangman-network
    volumes:
      - ./game-service:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  public-game-service:
    build: ./public-game
    expose:
      - "3005"
    environment:
      - NODE_ENV=development
      - DB_SERVICE_URL=http://db-service:3003
    networks:
      - hangman-network
    volumes:
      - ./public-game:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  public-game-service-2:
    build: ./public-game
    expose:
      - "3005"
    environment:
      - NODE_ENV=development
      - DB_SERVICE_URL=http://db-service:3003
    networks:
      - hangman-network
    volumes:
      - ./public-game:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  public-game-service-3:
    build: ./public-game
    expose:
      - "3005"
    environment:
      - NODE_ENV=development
      - DB_SERVICE_URL=http://db-service:3003
    networks:
      - hangman-network
    volumes:
      - ./public-game:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  chat-service:
    build: ./chat-service
    expose:
      - "3002"
    environment:
      - NODE_ENV=development
    networks:
      - hangman-network
    volumes:
      - ./chat-service:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  chat-service-2:
    build: ./chat-service
    expose:
      - "3002"
    environment:
      - NODE_ENV=development
    networks:
      - hangman-network
    volumes:
      - ./chat-service:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  chat-service-3:
    build: ./chat-service
    expose:
      - "3002"
    environment:
      - NODE_ENV=development
    networks:
      - hangman-network
    volumes:
      - ./chat-service:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  socket-server:
    build: ./socket-server
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://client:80
      - GAME_SERVICE_URL=http://game-service:3001
      - CHAT_SERVICE_URL=http://chat-service:3002
    networks:
      - hangman-network
    volumes:
      - ./socket-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - game-service
      - chat-service
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  socket-server-2:
    build: ./socket-server
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://client:80
      - GAME_SERVICE_URL=http://game-service:3001
      - CHAT_SERVICE_URL=http://chat-service:3002
    networks:
      - hangman-network
    volumes:
      - ./socket-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - game-service
      - chat-service
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  socket-server-3:
    build: ./socket-server
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://client:80
      - GAME_SERVICE_URL=http://game-service:3001
      - CHAT_SERVICE_URL=http://chat-service:3002
    networks:
      - hangman-network
    volumes:
      - ./socket-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - game-service
      - chat-service
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  hangman-network:
    driver: bridge